apiVersion: v1
kind: Service
metadata:
  name: messaging-app-blue-service
spec:
  selector:
    app: messaging-app-blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: messaging-app-green-service
spec:
  selector:
    app: messaging-app-green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: messaging-app-external-service
spec:
  selector:
    app: messaging-app-blue # Initially points to blue deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
